sudo: required
services:
  - docker

before_install:
  - docker build -t samhld/docker-react -f Dockerfile.dev .

script:
  - docker run samhld/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-419632218244"
  bucket_path: "docker-react"
  on:
    branch: master
  acess_key_id: $Access_Key_ID
  secrete_access_key:
    securte: "$AWS_SECRET_KEY"
